import * as vscode from 'vscode';

export const CONFIG_CLEAR_ALL_ICON = new vscode.ThemeIcon('clear-all');
export const CONFIG_ADD_ICON = new vscode.ThemeIcon('add');
export const CONFIG_PASS_ICON = new vscode.ThemeIcon('circle-filled', new vscode.ThemeColor('charts.green'));
export const CIRCLE_FILLED = new vscode.ThemeIcon('circle-filled');
export const CIRCLE_OUTLINE = new vscode.ThemeIcon('circle-outline');
export const ROCKET = new vscode.ThemeIcon('rocket');
export const ACCOUNT = new vscode.ThemeIcon('account');
export const CURRENT_ACCOUNT = new vscode.ThemeIcon('account', new vscode.ThemeColor('charts.green'));
export const KEY = new vscode.ThemeIcon('key');
export const FOLDER = new vscode.ThemeIcon('folder');
export const FOLDER_ACTIVE = new vscode.ThemeIcon('folder', new vscode.ThemeColor('charts.green'));
export const FOLDER_INTERRUPTED = new vscode.ThemeIcon('folder', new vscode.ThemeColor('charts.red'));
export const FILE = new vscode.ThemeIcon('file');
export const BROWSER = new vscode.ThemeIcon('browser');
export const LAYOUT = new vscode.ThemeIcon('layout');
export const GROUP_BY_REF_TYPE = new vscode.ThemeIcon('group-by-ref-type');
export const MILESTONE = new vscode.ThemeIcon('milestone');
export const MILESTONE_ACTIVE = new vscode.ThemeIcon('milestone', new vscode.ThemeColor('charts.green'));
export const MILESTONE_PAUSED = new vscode.ThemeIcon('milestone', new vscode.ThemeColor('charts.orange'));
export const MILESTONE_INTERRUPTED = new vscode.ThemeIcon('milestone', new vscode.ThemeColor('charts.red'));
export const TEST_VIEW_ICON = new vscode.ThemeIcon('test-view-icon');
export const BRACKET = new vscode.ThemeIcon('bracket');
export const WATCH = new vscode.ThemeIcon('watch');
export const TARGET = new vscode.ThemeIcon('target');
export const FILE_CODE = new vscode.ThemeIcon('file-code');
